# We only want the essentials for building the website.
# Other packages will make the environment bloat too much,
# therefore any notebooks added should preserve their outputs.
name: essays-on-data-science
channels:
  - conda-forge
dependencies:
  - python=3.8
  - conda
  - ipykernel
  - jax<=0.2.9
  - jaxlib<=0.1.57
  - jupyter
  - jupyterlab
  - mamba
  - matplotlib
  - pip
  - pre-commit>=1.20.0
  - pygments>=2.4.2
  - pyjanitor
  - seaborn
  - rdkit
  - jupyter-lsp
  - jupyterlab-lsp
  - python-language-server
  - jedi=0.17.2 # pinned because of one of the language server packages needing it
  - pip:
      - mkdocs
      - mkdocs-material
      - mkdocs-minify-plugin
      - mknotebooks
      - pymdown-extensions
      - proselint
      - neural-tangents
      - watermark
