site_name: Essays on Data Science
theme:
  name: "material"
  palette:
    primary: "light blue"
    accent: "light blue"
    icon:
      logo: "library_books"
  features:
    - tabs

nav:
  - Home: index.md
  - Computing:
      - Recursion: computing/recursion.md
  - Machine Learning:
      - An Introduction to Probability and Computational Bayesian Statistics: machine-learning/computational-bayesian-stats.md
      - Markov Models From The Bottom Up, with Python: machine-learning/markov-models.md
      - Dirichlet Processes and Hidden Markov Model Transition Matrices: machine-learning/generating-markov-chains-dirichlet.ipynb
      - Computational Representations of Message Passing: machine-learning/message-passing.md
      - Reimplementing and Testing Deep Learning Models: machine-learning/reimplementing-models.md
      - Differential Computing Explained: machine-learning/differential-computing-jax.md
      - Infinitely Wide Neural Networks: machine-learning/nngp.ipynb
  - Miscellaneous:
      - A Review of the Python Data Science Dashboarding Landscape in 2019: miscellaneous/dashboarding-landscape.md
      - How I Learned to Learn: miscellaneous/learning-to-learn.md
      - An Opinionated and Unofficial Guide to the PyData Ecosystem: miscellaneous/pydata-landscape.md
      - Static Sites and Apps On Your Own Dokku Server: miscellaneous/static-sites-on-dokku.md
      - Code Style Tools: miscellaneous/code-style-tools.md
  - Newsletter:
      - 2020:
          - May: newsletter/2020/05-may.md
          - June: newsletter/2020/06-june.md
          - July: newsletter/2020/07-july.md
          - August: newsletter/2020/08-august.md
          - September: newsletter/2020/09-september.md
          - October: newsletter/2020/10-october.md
          - November: newsletter/2020/11-november.md
          - December: newsletter/2020/12-december.md
  - Software Skills:
      - Importance: software-skills/index.md
      - Formatting your code: software-skills/code-formatting.md
      - Documenting your code: software-skills/documentation.md
      - A Data Scientist's Guide to Environment Variables: software-skills/environment-variables.md
      - Refactoring your code: software-skills/refactoring.md
      - Testing your code: software-skills/testing.md
  - Terminal Hacks:
      - Tools and Upgrades for your CLI: terminal/cli-tools.md
      - Using pre-commit git hooks to automate code checks: terminal/pre-commits.md
  - Workflow:
      - Practicing Code Review: workflow/code-review.md
      - Effective Git Commits in Data Science: workflow/effective-commit-messages.md
      - Principled Git-based Workflow in Collaborative Data Science Projects: workflow/gitflow.md
  - Supporters: supporters.md

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
  - mknotebooks:
      execute: true
      timeout: 600
      binder: true
      binder_service_name: "gh"
      binder_branch: "master"

# Taken from here: https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
markdown_extensions:
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - markdown.extensions.footnotes

extra_css:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js

google_analytics:
  - "UA-12498603-3"
  - "auto"

repo_name: "ericmjl/essays-on-data-science"
repo_url: "https://github.com/ericmjl/essays-on-data-science"

extra:
  social:
    - icon: "material/email"
      link: "http://www.shortwhale.com/ericmjl"
    - icon: "fontawesome/brands/github"
      link: "https://github.com/ericmjl"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/ericmjl"
    - icon: "fontawesome/brands/linkedin"
      link: "https://linkedin.com/in/ericmjl"
