# This GitHub workflow runs on every commit.
name: Website Preview

on: [pull_request]

jobs:
  build-website:
    name: "Website Preview"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      # https://github.com/marketplace/actions/setup-miniconda
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          channels: conda-forge
          environment-file: environment.yml
          use-mamba: true

      - name: Build website
        run: |
          source activate essays-on-data-science
          python -m ipykernel install --name essays-on-data-science --user
          mkdocs build --verbose --clean --strict

      # https://www.bradmcgonigle.com/blog/github-action-for-continuous-deployment
      # - NETLIFY_SITE_ID maps to the netlify site's API ID
      # - NETLIFY_AUTH_TOKEN maps to netlify's Personal Access Token that I set on a per-user basis
      - name: Netlify PR preview
        uses: netlify/actions/cli@master
        with:
          args: deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --dir=site/
