# This GitHub workflow runs on every commit.
name: Pull request checks

on:
  pull_request:

jobs:
# This GitHub workflow runs only on push to master.
# By this point, we are assuming that all checks on the PR,
# which are checked by the Azure Pipeline, have passed.
# The full pipeline is also leveraged here,
# as we don't want a broken website to be deployed anyways.

name: Pull request site previews

on: [pull_request]

jobs:
  build-website:
    name: "Build website"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      # See: https://github.com/marketplace/actions/setup-conda
      - uses: s-weigand/setup-conda@v1
        with:
          conda-channels: "conda-forge"

      - name: Build environment
        # if: steps.cache-environment.outputs.cache-hit != 'true'
        run: |
          conda install -c conda-forge mamba
          mamba env create -f environment.yml

      - name: Build website
        run: |
          source activate essays-on-data-science
          python -m ipykernel install --name essays-on-data-science --user
          mkdocs build --verbose --clean --strict

      # https://www.bradmcgonigle.com/blog/github-action-for-continuous-deployment
      # - NETLIFY_SITE_ID maps to the netlify site's API ID
      # - NETLIFY_AUTH_TOKEN maps to netlify's Personal Access Token that I set on a per-user basis
      - name: Netlify PR preview
        uses: netlify/actions/cli@master
        with:
          args: deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --dir=site/
